### PR TITLE
use bounded parameter type

### PR DESCRIPTION
**Pull request by wrover**
I faced a trouble using the service from Java code. It's not convenient and even it may be
impossible to pass `Class<ExtEntity>` to method declared to take `Class<Entity>`. But this
works in Groovy in your examples. So I decided to move to bounded generics and I found
them works well here. Since I have almost no experience in Groovy I migrated the service to
Java, but actually no one minds how it's implemented, the interface is what makes sense.

### CODE REVIEW

**Comment by mariodavid** [comment]
Hi Ilya,

Thanks for contribution. Will take a look at it shortly. 

I've not really java problems in mind while implementing (usually only making the interface a java file for better interoperability) but you may be totally right.

If everything is file i will just merge and release it.

Bye
Mario

**Comment by wrover** [comment]
Hi, Mario,

at first I tried to implement the service bean in Groovy according to modified interface, but than  realized that's not easy for me and just switched to Java. Actually it's exactly the same code. So if you consider interface changes make sense, you can just refactor existed Grovvy class accordingly instead of pulling new implementation.

Regards,
Ilia.

**Comment by wrover** [comment]
Hello Mario,
I would like to have the PR merged since I need it to publish my depending component. 
Could you take a look?
Thanks in advance.
Ilia.

**Comment by mariodavid** [comment]
hi,

sorry for not getting back to you. I plan to merge it together with 6.9 support and release it in 0.3.0. Will do it in the next days...

Bye
Mario

**Comment by mariodavid** [comment]
copied stuff over to #2 and merged. Will close this one. Thanks for your contribution!

**Comment by wrover** [comment]
Thank you, Mario.

**Pull request closed without merging**
